export enum InvestmentType {
  STOCKS = "Stocks",
  BONDS = "Bonds",
  MUTUAL_FUNDS = "Mutual Funds",
  ETFs = "ETFs (Exchange-Traded Funds)",
  REITS = "REITs (Real Estate Investment Trusts)",
  CRYPTOCURRENCY = "Cryptocurrency",
  COMMODITIES = "Commodities",
  FOREX = "Foreign Exchange",
  REAL_ESTATE = "Real Estate",
  PEER_TO_PEER_LENDING = "Peer-to-Peer Lending",
  CERTIFICATES_OF_DEPOSIT = "Certificates of Deposit (CDs)",
  SAVINGS_ACCOUNTS = "Savings Accounts",
  INDEX_FUNDS = "Index Funds",
  HEDGE_FUNDS = "Hedge Funds",
  PRIVATE_EQUITY = "Private Equity",
  ANNUITIES = "Annuities",
  OPTIONS = "Options",
  FUTURES = "Futures",
  GOLD = "Gold",
  SILVER = "Silver",
  ART = "Art",
  COLLECTIBLES = "Collectibles",
  VENTURE_CAPITAL = "Venture Capital",
  INSURANCE = "Insurance",
  GOVERNMENT_BONDS = "Government Bonds",
  CORPORATE_BONDS = "Corporate Bonds",
  MUNICIPAL_BONDS = "Municipal Bonds",
  TREASURY_BONDS = "Treasury Bonds",
  MONEY_MARKET_FUNDS = "Money Market Funds",
  PENSION_FUNDS = "Pension Funds",
  ESOP = "Employee Stock Ownership Plan (ESOP)",
  UNIT_TRUSTS = "Unit Trusts",
  STRUCTURED_PRODUCTS = "Structured Products",
  SOCIAL_IMPACT_INVESTMENTS = "Social Impact Investments",
  ESG_INVESTMENTS = "ESG (Environmental, Social, and Governance) Investments",
  PRECIOUS_METALS = "Precious Metals",
  AGRICULTURAL_PRODUCTS = "Agricultural Products",
  INFRASTRUCTURE_INVESTMENTS = "Infrastructure Investments",
}

export enum ModalType {
  ADD_ITEMS_SECTION = "add-items-section",
  ADD_MAIN_SECTION = "add-main-section",
  ADD_SUB_SECTION = "add-sub-section",
  CONFIRM_DELETE_ITEM = "confirm-delete-item",
  CONFIRM_DELETE_MAIN_SECTION = "confirm-delete-main-section",
  EDIT_ITEMS_SECTION = "edit-items-section",
  EDIT_MAIN_SECTION = "edit-main-section",
  EDIT_SUB_SECTION = "edit-sub-section",
}
